name: Feature Request
description: Submit a proposal for a new feature
labels: ["type: feature request"]
body:
  - type: markdown
    attributes:
      value: "
        Thank you for taking the time to propose a new feature!
        
  - type: textarea
    attributes:
      label: Feature description
      description: Describe your feature proposal
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use case
      description: Describe what you are trying to achive
