[package]
name = "testing"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-sdk-dynamodb = "0.21.0"
aws-smithy-client = { version = "0.51.0", features = ["test-util"] }
aws-smithy-http = "0.51.0"
lambda_http = { git = "https://github.com/awslabs/aws-lambda-rust-runtime", rev ="8d7c0eb" }