version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ArkStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gnkcjj27wkwy"
s3_prefix = "ArkStack"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
