[package]
name = "tive-core"
authors = ["Kevin G. <ge.kevin.a@gmail.com>"]
version = "0.1.0"
edition = "2021"
rust-version = "1.64"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
postgres = "0.19.4"