name: CI Rust Lambdas

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - 'main'
    paths:
      - 'lambdas/**'
  push:
    branches:
      - 'main'
    paths:
      - 'lambdas/**'

jobs:
  cargo-fmt:
    name: Cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
      - run: |
          cd lambdas
          cargo fmt --all --check

  cargo-clippy:
    name: Cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy
      - run: |
          cd lambdas
          cargo clippy --all-targets -- -D warnings

  cargo-test:
    name: Cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - run: |
          cd lambdas
          cargo test
