name: CI Rust Scanner

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    branches:
      - "main"
    paths:
      - "ark_scanner/**"
  push:
    branches:
      - "main"
    paths:
      - "ark_scanner/**"

jobs:
  cargo-fmt:
    name: Cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt

      - name: Run formatter checks
        working-directory: ark_scanner
        run: cargo fmt --all --check

  cargo-clippy:
    name: Cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy

      - name: Run linter
        working-directory: ark_scanner
        run: cargo clippy --all-targets -- -D warnings

  cargo-test:
    name: Cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.65.0
          profile: minimal

      - name: Run tests
        working-directory: ark_scanner
        run: cargo test
